/*
 * Copyright © 2025-2026 Metreeca srl
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { boolean } from "../../../boolean.js";
import { reference } from "../../../reference.js";
import { property, resource } from "../../../resource.js";
import { optional, required, type State } from "../../../value.js";
import { ec2u, Entity, rdfs } from "../terms/ec2u.js";
import { Dataset } from "./index.js";
import { University } from "./universities/index.js";


export type Resource = State<typeof Resource>


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export function Resource() {
	return resource({

		extends: Entity,
		namespace: ec2u

	}, {

		generated: property({

			description: { en: "Flags resources wholly or partially generated by AI tools." }

		}, optional(boolean)),

		dataset: property({

			forward: ec2u,
			reverse: rdfs.member

		}, required(reference(Dataset))),

		university: optional(reference(University))

	});
}
